### PR TITLE
Refactored IGameService Part 1

### PR DESCRIPTION
**Pull request by ramonB1996**
- Refactored `IGameService` into abstract `Game` class.
- `GameFeatures` now in separate classes in the containing folder of the game.
- Simplified some methods to be properties

This is part 1, needs some more refactoring to improve the extensibility and decoupling of the code :)

The project builds and the tests pass. Please check if the games still run, I did not have time to run it myself yet. 
Feel free to change anything about the PR or comment on it ;)

### CODE REVIEW

**Comment by ramonB1996** [comment]
Can this PR be merged you think @hertelukas ? :)

**Comment by hertelukas** [comment]
I already reviewed parts of it. As this is a really large refactor, I need some time haha. Maybe smaller changes per PR would be better in the future, then I can review them faster. :)

**Comment by ramonB1996** [comment]
@hertelukas I understand, you are right indeed. Will do smaller PR's in the future. Take your time and I will see when it is merged. Will start on the next part after the merge :)

**Comment by hertelukas** [comment]
@ramonB1996 Sorry that it took me so long, I'll be way faster for small PRs

**Comment by ramonB1996** [comment]
Thanks for the merge! No worries 😉

**Pull request merged**
